Day 2
Creating and inspecting DataFrames
 Selecting rows and columns with .loc and .iloc
 Handling missing values
 Removing duplicates and correcting data types
 Merging datasets
 A practical data-cleaning challenge

In [12]:
import pandas as pd
import numpy as np

data = {
    "OrderID": [101, 102, 103, 104, 105, 105, 106, 107],
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor",
                "Mouse", "Mouse", "Desk", "Laptop"],
    "Category": ["Electronics", "Electronics", "Electronics",
                 "Electronics", "Electronics", "Electronics",
                 "Furniture", "Electronics"],
    "Quantity": [2, 5, 3, np.nan, 4, 4, 1, 1],
    "UnitPrice": [800, 20, 50, 250, 20, 20, 300, 800],
    "Region": ["North", "South", "North", "West",
               "South", "South", "East", "North"]
}

df = pd.DataFrame(data)
print(df)

   OrderID   Product     Category  Quantity  UnitPrice Region
0      101    Laptop  Electronics       2.0        800  North
1      102     Mouse  Electronics       5.0         20  South
2      103  Keyboard  Electronics       3.0         50  North
3      104   Monitor  Electronics       NaN        250   West
4      105     Mouse  Electronics       4.0         20  South
5      105     Mouse  Electronics       4.0         20  South
6      106      Desk    Furniture       1.0        300   East
7      107    Laptop  Electronics       1.0        800  North

In [13]:
df.describe().round(2)

       OrderID  Quantity  UnitPrice
count     8.00      7.00       8.00
mean    104.12      2.86     282.50
std       2.03      1.57     337.59
min     101.00      1.00      20.00
25%     102.75      1.50      20.00
50%     104.50      3.00     150.00
75%     105.25      4.00     425.00
max     107.00      5.00     800.00

In [14]:
df.shape

(8, 6)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    8 non-null      int64
 1   Product    8 non-null      object
 2   Category   8 non-null      object
 3   Quantity   7 non-null      float64
 4   UnitPrice  8 non-null      int64
 5   Region     8 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 516.0+ bytes

In [16]:
df.isna().sum()

OrderID      0
Product      0
Category     0
Quantity     1
UnitPrice    0
Region       0
dtype: int64

In [17]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [18]:
df.duplicated(subset="OrderID")

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [19]:
df[df.duplicated(subset="OrderID", keep=False)]

   OrderID Product     Category  Quantity  UnitPrice Region
4      105   Mouse  Electronics       4.0         20  South
5      105   Mouse  Electronics       4.0         20  South

In [20]:
df.duplicated(subset="OrderID").sum()

1

In [21]:
df_clean=df.drop_duplicates(subset="OrderID",keep="first")

In [22]:
df_clean.info

<bound method DataFrame.info of    OrderID   Product     Category  Quantity  UnitPrice Region
0      101    Laptop  Electronics       2.0        800  North
1      102     Mouse  Electronics       5.0         20  South
2      103  Keyboard  Electronics       3.0         50  North
3      104   Monitor  Electronics       NaN        250   West
4      105     Mouse  Electronics       4.0         20  South
6      106      Desk    Furniture       1.0        300   East
7      107    Laptop  Electronics       1.0        800  North>

In [23]:
df_clean.isna().sum()

OrderID      0
Product      0
Category     0
Quantity     1
UnitPrice    0
Region       0
dtype: int64

In [24]:
df_clean[df_clean["Quantity"].isna()]

   OrderID  Product     Category  Quantity  UnitPrice Region
3      104  Monitor  Electronics       NaN        250   West

In [25]:
missing_pct=(((df_clean.isna().sum())/df_clean.shape[0])*100).round(2)

In [26]:
missing_pct[missing_pct>0]

Quantity    14.29
dtype: float64

In [27]:
median_quantity=df_clean["Quantity"].median()
print(median_quantity)

2.5

In [28]:
df_imputed=df_clean.copy()
df_imputed["Quantity"]=df_imputed["Quantity"].fillna(median_quantity)

In [42]:
df_no_missing=df_clean.dropna(subset=["Quantity"]).copy()

In [43]:
df_no_missing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    6 non-null      int64
 1   Product    6 non-null      object
 2   Category   6 non-null      object
 3   Quantity   6 non-null      float64
 4   UnitPrice  6 non-null      int64
 5   Region     6 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 336.0+ bytes

In [31]:
df_no_missing["Quantity"].isna().sum

<bound method Series.sum of 0    False
1    False
2    False
4    False
6    False
7    False
Name: Quantity, dtype: bool>

In [32]:
df_no_missing.describe().round(2)

       OrderID  Quantity  UnitPrice
count     6.00      6.00       6.00
mean    104.00      2.67     331.67
std       2.37      1.63     377.70
min     101.00      1.00      20.00
25%     102.25      1.25      27.50
50%     104.00      2.50     175.00
75%     105.75      3.75     675.00
max     107.00      5.00     800.00

In [33]:
df_clean.loc[3,"Product"]
df_clean.loc[3,["Product","UnitPrice"]]
df_clean.iloc[3,1]

'Monitor'

In [34]:
df_clean

   OrderID   Product     Category  Quantity  UnitPrice Region
0      101    Laptop  Electronics       2.0        800  North
1      102     Mouse  Electronics       5.0         20  South
2      103  Keyboard  Electronics       3.0         50  North
3      104   Monitor  Electronics       NaN        250   West
4      105     Mouse  Electronics       4.0         20  South
6      106      Desk    Furniture       1.0        300   East
7      107    Laptop  Electronics       1.0        800  North

In [35]:
df_clean.loc[6,"Product"]

'Desk'

In [36]:
df_clean.iloc[6,1]

'Laptop'

In [37]:
df_clean=df_clean.reset_index(drop=True)
df_clean

   OrderID   Product     Category  Quantity  UnitPrice Region
0      101    Laptop  Electronics       2.0        800  North
1      102     Mouse  Electronics       5.0         20  South
2      103  Keyboard  Electronics       3.0         50  North
3      104   Monitor  Electronics       NaN        250   West
4      105     Mouse  Electronics       4.0         20  South
5      106      Desk    Furniture       1.0        300   East
6      107    Laptop  Electronics       1.0        800  North

In [38]:
df_clean.dtypes

OrderID        int64
Product       object
Category      object
Quantity     float64
UnitPrice      int64
Region        object
dtype: object

In [44]:
df_no_missing["Quantity"]=df_no_missing["Quantity"].astype(int)

In [45]:
df_no_missing

   OrderID   Product     Category  Quantity  UnitPrice Region
0      101    Laptop  Electronics         2        800  North
1      102     Mouse  Electronics         5         20  South
2      103  Keyboard  Electronics         3         50  North
4      105     Mouse  Electronics         4         20  South
5      106      Desk    Furniture         1        300   East
6      107    Laptop  Electronics         1        800  North

In [46]:
orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104, 105],
    "ProductID": [1, 2, 1, 3, 2],
    "Quantity": [2, 5, 1, 3, 4]
})

products = pd.DataFrame({
    "ProductID": [1, 2, 3, 4],
    "ProductName": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "UnitPrice": [800, 20, 50, 250]
})

In [47]:
print(orders)
print(products)

   OrderID  ProductID  Quantity
0      101          1         2
1      102          2         5
2      103          1         1
3      104          3         3
4      105          2         4
   ProductID ProductName  UnitPrice
0          1      Laptop        800
1          2       Mouse         20
2          3    Keyboard         50
3          4     Monitor        250

In [49]:
merged=pd.merge(orders,products,on="ProductID",how="inner")
print(merged)

   OrderID  ProductID  Quantity ProductName  UnitPrice
0      101          1         2      Laptop        800
1      102          2         5       Mouse         20
2      103          1         1      Laptop        800
3      104          3         3    Keyboard         50
4      105          2         4       Mouse         20

In [52]:
merge_left=pd.merge(orders,products,on="ProductID",how="left")
print(merge_left)

   OrderID  ProductID  Quantity ProductName  UnitPrice
0      101          1         2      Laptop        800
1      102          2         5       Mouse         20
2      103          1         1      Laptop        800
3      104          3         3    Keyboard         50
4      105          2         4       Mouse         20

In [56]:
order_test=pd.concat([
    orders, pd.DataFrame({
        "OrderID":[106], "ProductID":[5], "Quantity":[2]
    })
],ignore_index=True)
order_test

   OrderID  ProductID  Quantity
0      101          1         2
1      102          2         5
2      103          1         1
3      104          3         3
4      105          2         4
5      106          5         2

In [57]:
merge_test_left=pd.merge(order_test,products,on="ProductID",how="left")
merge_test_left

   OrderID  ProductID  Quantity ProductName  UnitPrice
0      101          1         2      Laptop      800.0
1      102          2         5       Mouse       20.0
2      103          1         1      Laptop      800.0
3      104          3         3    Keyboard       50.0
4      105          2         4       Mouse       20.0
5      106          5         2         NaN        NaN

In [58]:
merge_right=pd.merge(order_test,products,on="ProductID",how="right")
merge_right

   OrderID  ProductID  Quantity ProductName  UnitPrice
0    101.0          1       2.0      Laptop        800
1    103.0          1       1.0      Laptop        800
2    102.0          2       5.0       Mouse         20
3    105.0          2       4.0       Mouse         20
4    104.0          3       3.0    Keyboard         50
5      NaN          4       NaN     Monitor        250

In [60]:
merge_outer=pd.merge(order_test,products,on="ProductID",how="outer")
merge_outer

   OrderID  ProductID  Quantity ProductName  UnitPrice
0    101.0          1       2.0      Laptop      800.0
1    103.0          1       1.0      Laptop      800.0
2    102.0          2       5.0       Mouse       20.0
3    105.0          2       4.0       Mouse       20.0
4    104.0          3       3.0    Keyboard       50.0
5      NaN          4       NaN     Monitor      250.0
6    106.0          5       2.0         NaN        NaN

In [72]:
merge_final=pd.merge(order_test, products,on="ProductID",how="inner")
merge_final["Revenue"]=merge_final["Quantity"]*merge_final["UnitPrice"].copy()

In [74]:
merge_final

   OrderID  ProductID  Quantity ProductName  UnitPrice  Revenue
0      101          1         2      Laptop        800     1600
1      102          2         5       Mouse         20      100
2      103          1         1      Laptop        800      800
3      104          3         3    Keyboard         50      150
4      105          2         4       Mouse         20       80